### ISSUE TITLE
TaffyDB Warning.. But otherwise Awesome!

### ISSUE THREAD

**Issue by JimLidel** [amekusa/docolatte#3]
I've looked at as many JSDoc templates as I could find and yours is easily my favorite! 
I installed it but got the high severity vulnerability message in npm so I had to uninstall since security is a big deal around here.
I guess JSDoc has moved on from using TaffyDB? If you could update the template I would happily use it and highly recommend it to all my coworkers.

Thanks for all the work!

**Comment by amekusa** [comment]
Hi, thank you for checking it.
The security warning for TaffyDB came from JSDoc 3 as mentioned here:
https://github.com/jsdoc/jsdoc/issues/2013

The warning says "TaffyDB can allow access to any data items in the DB"
as reported here: https://github.com/advisories/GHSA-mxhp-79qh-mcx6

As JSDoc dev stated, I think this "vulnerability" is not a problem for our use-case since TaffyDB is only used for storing data of your source code collected by JSDoc for documentation.

Also, JSDoc dev replaced TaffyDB with an alternate lib (`@jsdoc/salty`) at this point:
https://github.com/jsdoc/jsdoc/commit/d723ed5603762942b843f1873848d7738224a06b#diff-51b56a90552ff973153dfd5eb771d70603626a199fe9ce9ec3f5b99e5370c68a

So I've replaced the TaffyDB reference with `@jsdoc/salty` in Docolatte as well at this point:
https://github.com/amekusa/docolatte/commit/ff6ed7828a2abd33f438be0946c92a9998970fb1

I'm afraid but I think there is nothing else I can do for the said warning other than migrating Docolatte to JSDoc 4.
But I don't have enough time to do it any time soon.
However, I think this is not a big deal at all. TaffyDB is in-memory database. You won't store critical information (i.e. credit card info) into it.

**Comment by amekusa** [comment]
That said, I understand people don't like the warning appears when install Docolatte.
So I'm considering removing `jsdoc` from dependencies in `package.json` just for turning off the warning just like the other JSDoc 3 themes did. Assuming most users are using JSDoc as a global package, this change would be nothing harm.

**Comment by amekusa** [comment]
Sorry for late, but now **the warning is gone** at the latest version 3.5.1 👍 I really appreciate your feedback. Thank you.
